$files = @(
    '00_PROGRAM_CHARTER.md', '01_TRUTH_AUDIT_OF_PREVIOUS_CLAIMS.md', '02_LOCAL_GIT_DEPLOY_PRODUCTION_PARITY.md',
    '03_SECURITY_AND_SECRET_INCIDENT.md', '04_CURRENT_FRONTEND_ARCHITECTURE.md', '05_RENDER_TREE_AND_LAYOUT_OWNERSHIP.md',
    '06_DESIGN_MD_REALITY_AND_CAPABILITIES.md', '07_DESIGN_TOKEN_PIPELINE.md', '08_CSS_CASCADE_AND_SPECIFICITY.md',
    '09_HARDCODE_AND_OVERRIDE_INVENTORY.md', '10_APPSHELL_GEOMETRY.md', '11_PRIMARY_AND_CONTEXTUAL_NAVIGATION.md',
    '12_HEADER_AND_TOOLBAR_CONSOLIDATION.md', '13_GLASS_SURFACES_AND_BACKDROP_ROOTS.md', '14_PRIMITIVE_COMPONENT_INVENTORY.md',
    '15_DIALOG_SHEET_POPOVER_PORTALS.md', '16_GRID_SPACING_AND_DENSITY.md', '17_PAGE_AND_MODULE_SHELLS.md',
    '18_KANBAN_RECOVERY.md', '19_ROUTE_FLASH_AND_HYDRATION.md', '20_PWA_CACHE_AND_DEPLOY_PARITY.md',
    '21_ACCESSIBILITY_BASELINE.md', '22_FRONTEND_PERFORMANCE_BASELINE.md', '23_RERENDER_AND_EFFECT_AUDIT.md',
    '24_DATA_ERRORS_VISIBLE_IN_UI.md', '25_FINANCIAL_RELATIONSHIP_REVALIDATION.md', '26_MODULE_BY_MODULE_UI_AUDIT.md',
    '27_VISUAL_TEST_MATRIX.md', '28_FUNCTIONAL_REGRESSION_MATRIX.md', '29_BREAKPOINT_SCREENSHOTS.md',
    '30_LEGACY_TO_CANONICAL_MIGRATION.md', '31_DEPRECATION_AND_REMOVAL_GATES.md', '32_CORRECTIVE_EXECUTION_PLAN.md',
    '33_EXECUTION_LOG.md', '34_EVIDENCE_INDEX.md', '35_PRODUCTION_READINESS.md', '36_OPEN_RISKS_AND_BLOCKERS.md'
)

New-Item -ItemType Directory -Force -Path docs\frontend-ui-recovery

foreach ($file in $files) {
    $path = Join-Path -Path 'docs\frontend-ui-recovery' -ChildPath $file
    New-Item -ItemType File -Force -Path $path
    Set-Content -Path $path -Value "# $file"
}
