import { z } from "zod";

export interface ActionDefinition<TIn extends z.ZodTypeAny = z.ZodTypeAny> {
  code: string;
  name: string;
  description: string;
  domain: "crm" | "trips" | "financial" | "documents" | "support" | "operational";
  inputSchema: TIn;
  allowedRoles: string[];
  requiresConfirmation: boolean;
  riskLevel: "low" | "medium" | "high";
}

export const ActionRegistry: Record<string, ActionDefinition<any>> = {
  // CRM Domain
  create_lead: {
    code: "create_lead",
    name: "Criar Lead",
    description: "Cadastra um novo lead interessado em um destino no CRM",
    domain: "crm",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "low",
    inputSchema: z.object({
      name: z.string().min(1, "Nome é obrigatório"),
      email: z.string().email("E-mail inválido").optional().nullable(),
      phone: z.string().optional().nullable(),
      destination: z.string().min(1, "Destino é obrigatório"),
      notes: z.string().optional().nullable(),
    }),
  },
  update_lead: {
    code: "update_lead",
    name: "Atualizar Lead",
    description: "Atualiza os dados cadastrais de um lead existente",
    domain: "crm",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "medium",
    inputSchema: z.object({
      leadId: z.string().uuid("ID do lead inválido"),
      name: z.string().optional(),
      email: z.string().email("E-mail inválido").optional().nullable(),
      phone: z.string().optional().nullable(),
      destination: z.string().optional(),
      notes: z.string().optional().nullable(),
    }),
  },
  change_lead_stage: {
    code: "change_lead_stage",
    name: "Alterar Estágio",
    description: "Altera o estágio do lead no funil do CRM",
    domain: "crm",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "low",
    inputSchema: z.object({
      leadId: z.string().uuid("ID do lead inválido"),
      stage: z.enum(["new", "contacted", "proposal", "negotiation", "won", "lost"]),
    }),
  },
  create_client: {
    code: "create_client",
    name: "Criar Cliente",
    description: "Cadastra um novo cliente no sistema",
    domain: "crm",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "medium",
    inputSchema: z.object({
      name: z.string().min(1, "Nome é obrigatório"),
      document: z.string().optional().nullable(),
      email: z.string().email("E-mail inválido").optional().nullable(),
      phone: z.string().optional().nullable(),
      birthDate: z.string().optional().nullable(),
    }),
  },

  // Trips Domain
  add_traveler: {
    code: "add_traveler",
    name: "Adicionar Viajante",
    description: "Vincula um viajante a uma viagem específica",
    domain: "trips",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "low",
    inputSchema: z.object({
      tripId: z.string().uuid("ID da viagem inválido"),
      name: z.string().min(1, "Nome é obrigatório"),
      document: z.string().optional().nullable(),
      phone: z.string().optional().nullable(),
      birthDate: z.string().optional().nullable(),
    }),
  },
  update_traveler: {
    code: "update_traveler",
    name: "Atualizar Viajante",
    description: "Atualiza os dados de um viajante/passageiro",
    domain: "trips",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "medium",
    inputSchema: z.object({
      travelerId: z.string().uuid("ID do viajante inválido"),
      name: z.string().optional(),
      document: z.string().optional().nullable(),
      phone: z.string().optional().nullable(),
      birthDate: z.string().optional().nullable(),
    }),
  },
  start_quote: {
    code: "start_quote",
    name: "Iniciar Cotação",
    description: "Inicia uma nova cotação ou orçamento de viagem",
    domain: "trips",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "low",
    inputSchema: z.object({
      clientId: z.string().uuid("ID do cliente é obrigatório"),
      title: z.string().min(1, "Título é obrigatório"),
      destination: z.string().min(1, "Destino é obrigatório"),
      passengersCount: z.number().int().min(1).default(1),
      travelDate: z.string().optional().nullable(),
    }),
  },
  update_quote_as_proposal: {
    code: "update_quote_as_proposal",
    name: "Criar Proposta",
    description: "Gera uma proposta comercial de viagem vinculada a uma cotação",
    domain: "trips",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "medium",
    inputSchema: z.object({
      quoteId: z.string().uuid("ID da cotação inválido"),
      title: z.string().min(1, "Título da proposta é obrigatório"),
      totalAmount: z.number().positive("Valor total deve ser positivo"),
      notes: z.string().optional().nullable(),
    }),
  },
  quote_create: {
    code: "quote_create",
    name: "Criar Cotação VibeTour",
    description: "Cria uma nova cotação inteligente com análise de cenários logísticos",
    domain: "crm",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "low",
    inputSchema: z.object({
      destination: z.string().min(1, "Destino é obrigatório"),
      origin: z.string().default("CXP"),
      startDate: z.string().optional().nullable(),
      endDate: z.string().optional().nullable(),
      paxAdults: z.number().int().min(1).default(2),
      paxChildren: z.number().int().min(0).default(0),
      budget: z.number().optional().nullable(),
      clientId: z.string().uuid().optional().nullable(),
      leadId: z.string().uuid().optional().nullable(),
    }),
  },
  quote_compare: {
    code: "quote_compare",
    name: "Comparar Cenários",
    description: "Compara as alternativas e scorecards de pacotes da cotação",
    domain: "crm",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: false,
    riskLevel: "low",
    inputSchema: z.object({
      quoteRequestId: z.string().uuid("ID da cotação é obrigatório"),
    }),
  },
  add_hotel: {
    code: "add_hotel",
    name: "Adicionar Hotel",
    description: "Adiciona uma reserva de hotel a uma viagem ou proposta",
    domain: "trips",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "low",
    inputSchema: z.object({
      tripId: z.string().uuid("ID da viagem/proposta inválido"),
      hotelName: z.string().min(1, "Nome do hotel é obrigatório"),
      checkIn: z.string().min(1, "Data de check-in é obrigatória"),
      checkOut: z.string().min(1, "Data de check-out é obrigatória"),
      roomType: z.string().optional().nullable(),
      locator: z.string().optional().nullable(),
    }),
  },
  add_flight: {
    code: "add_flight",
    name: "Adicionar Voo",
    description: "Adiciona um trecho aéreo a uma viagem ou proposta",
    domain: "trips",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "low",
    inputSchema: z.object({
      tripId: z.string().uuid("ID da viagem/proposta inválido"),
      airline: z.string().min(1, "Companhia aérea é obrigatória"),
      flightNumber: z.string().min(1, "Número do voo é obrigatório"),
      fromCode: z.string().length(3, "Origem (IATA) deve ter 3 letras"),
      toCode: z.string().length(3, "Destino (IATA) deve ter 3 letras"),
      departureTime: z.string().min(1, "Data/hora de partida é obrigatória"),
      arrivalTime: z.string().optional().nullable(),
      locator: z.string().optional().nullable(),
    }),
  },
  create_trip: {
    code: "create_trip",
    name: "Criar Viagem",
    description: "Cria uma viagem confirmada a partir de uma proposta aprovada",
    domain: "trips",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "medium",
    inputSchema: z.object({
      proposalId: z.string().uuid("ID da proposta é obrigatório"),
      title: z.string().min(1, "Título da viagem é obrigatório"),
      startDate: z.string().min(1, "Data de início é obrigatória"),
      endDate: z.string().min(1, "Data de fim é obrigatória"),
    }),
  },
  query_trip: {
    code: "query_trip",
    name: "Consultar Viagem",
    description: "Busca informações sobre uma viagem e seus passageiros",
    domain: "trips",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: false,
    riskLevel: "low",
    inputSchema: z.object({
      query: z.string().min(1, "Termo de busca é obrigatório"),
    }),
  },

  // Operational Domain
  create_task: {
    code: "create_task",
    name: "Criar Tarefa",
    description: "Cria uma tarefa operacional vinculada a uma viagem ou operador",
    domain: "operational",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "low",
    inputSchema: z.object({
      title: z.string().min(1, "Título da tarefa é obrigatório"),
      dueDate: z.string().optional().nullable(),
      assignedTo: z.string().uuid().optional().nullable(),
      tripId: z.string().uuid().optional().nullable(),
      priority: z.enum(["low", "medium", "high"]).default("medium"),
    }),
  },
  create_ticket: {
    code: "create_ticket",
    name: "Criar Ticket",
    description: "Abre um ticket de suporte ou pós-vendas",
    domain: "support",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "low",
    inputSchema: z.object({
      subject: z.string().min(1, "Assunto é obrigatório"),
      clientId: z.string().uuid("ID do cliente é obrigatório"),
      description: z.string().min(1, "Descrição é obrigatória"),
      priority: z.enum(["low", "normal", "high", "urgent"]).default("normal"),
    }),
  },
  register_payment: {
    code: "register_payment",
    name: "Registrar Pagamento",
    description: "Registra uma transação ou recebimento financeiro",
    domain: "financial",
    allowedRoles: ["agency_admin", "finance"],
    requiresConfirmation: true,
    riskLevel: "high",
    inputSchema: z.object({
      tripId: z.string().uuid("ID da viagem é obrigatório"),
      amount: z.number().positive("Valor deve ser positivo"),
      method: z.enum(["pix", "credit_card", "bank_transfer", "cash", "other"]),
      dueDate: z.string().optional().nullable(),
      notes: z.string().optional().nullable(),
    }),
  },
  query_installments: {
    code: "query_installments",
    name: "Consultar Parcelas",
    description: "Consulta as parcelas e recebimentos pendentes de uma viagem",
    domain: "financial",
    allowedRoles: ["agency_admin", "finance", "agent"],
    requiresConfirmation: false,
    riskLevel: "low",
    inputSchema: z.object({
      tripId: z.string().uuid("ID da viagem é obrigatório"),
    }),
  },
  generate_contract: {
    code: "generate_contract",
    name: "Gerar Contrato",
    description: "Gera e envia o contrato de prestação de serviços de viagem",
    domain: "documents",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "high",
    inputSchema: z.object({
      tripId: z.string().uuid("ID da viagem é obrigatório"),
      clientId: z.string().uuid("ID do cliente é obrigatório"),
      templateId: z.string().optional().nullable(),
    }),
  },
  generate_voucher: {
    code: "generate_voucher",
    name: "Gerar Voucher",
    description: "Gera o voucher oficial com dados de serviços para o viajante",
    domain: "documents",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "medium",
    inputSchema: z.object({
      tripId: z.string().uuid("ID da viagem é obrigatório"),
      passengerIds: z.array(z.string().uuid()).optional(),
      notes: z.string().optional().nullable(),
    }),
  },
  query_supplier: {
    code: "query_supplier",
    name: "Consultar Fornecedor",
    description: "Busca informações cadastrais ou contatos de um fornecedor",
    domain: "operational",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: false,
    riskLevel: "low",
    inputSchema: z.object({
      query: z.string().min(1, "Termo de busca é obrigatório"),
    }),
  },
  start_ocr: {
    code: "start_ocr",
    name: "Iniciar OCR",
    description: "Inicia extração de dados inteligente de um arquivo de voucher/passaporte",
    domain: "documents",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "low",
    inputSchema: z.object({
      fileUrl: z.string().url("URL de arquivo inválida"),
      ocrType: z.enum(["voucher", "passport", "boleto", "proposal"]),
    }),
  },
  query_groups: {
    code: "query_groups",
    name: "Consultar Grupos",
    description: "Busca informações sobre grupos terrestres ou fretamentos ativos",
    domain: "operational",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: false,
    riskLevel: "low",
    inputSchema: z.object({
      query: z.string().min(1, "Termo de busca é obrigatório"),
    }),
  },
  update_rooming: {
    code: "update_rooming",
    name: "Atualizar Rooming",
    description: "Atualiza a distribuição de leitos/apartamentos de um grupo",
    domain: "operational",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "medium",
    inputSchema: z.object({
      groupId: z.string().uuid("ID do grupo inválido"),
      roomingData: z.array(
        z.object({
          roomNumber: z.number().int(),
          passengerIds: z.array(z.string().uuid()),
          roomType: z.string(),
        }),
      ),
    }),
  },
  generate_report: {
    code: "generate_report",
    name: "Gerar Relatório",
    description: "Gera relatórios operacionais ou financeiros da agência",
    domain: "financial",
    allowedRoles: ["agency_admin"],
    requiresConfirmation: true,
    riskLevel: "high",
    inputSchema: z.object({
      reportType: z.enum(["financial_summary", "sales_by_agent", "destination_ranking"]),
      startDate: z.string().min(1, "Data inicial é obrigatória"),
      endDate: z.string().min(1, "Data final é obrigatória"),
    }),
  },
  create_visa: {
    code: "create_visa",
    name: "Criar Processo de Visto",
    description: "Inicia um novo processo de visto consular para um cliente",
    domain: "operational",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "medium",
    inputSchema: z.object({
      clientId: z.string().uuid("ID do cliente inválido"),
      country: z.string().min(1, "País do visto é obrigatório"),
      category: z.string().min(1, "Categoria do visto é obrigatória"),
      expectedDate: z.string().optional().nullable(),
      interviewDate: z.string().optional().nullable(),
      notes: z.string().optional().nullable(),
    }),
  },
  add_insurance: {
    code: "add_insurance",
    name: "Adicionar Seguro Viagem",
    description: "Adiciona uma apólice de seguro de viagem a um voucher",
    domain: "trips",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "low",
    inputSchema: z.object({
      tripId: z.string().uuid("ID da viagem inválido"),
      provider: z.string().min(1, "Provedor do seguro é obrigatório"),
      policyNumber: z.string().min(1, "Número da apólice é obrigatório"),
      coverageLimit: z.string().optional().nullable(),
      notes: z.string().optional().nullable(),
    }),
  },
  send_whatsapp_template: {
    code: "send_whatsapp_template",
    name: "Enviar Template WhatsApp",
    description: "Dispara uma mensagem de modelo via WhatsApp para o cliente",
    domain: "operational",
    allowedRoles: ["agency_admin", "agent"],
    requiresConfirmation: true,
    riskLevel: "medium",
    inputSchema: z.object({
      clientId: z.string().uuid("ID do cliente inválido"),
      templateName: z.enum(["welcome", "voucher_ready", "payment_receipt", "contract_sign"]),
      phoneNumber: z.string().min(1, "Número de telefone é obrigatório"),
    }),
  },
  apply_discount_or_fee: {
    code: "apply_discount_or_fee",
    name: "Aplicar Desconto ou Taxa",
    description: "Aplica um desconto ou taxa de serviço sobre o total de uma proposta",
    domain: "financial",
    allowedRoles: ["agency_admin", "finance"],
    requiresConfirmation: true,
    riskLevel: "high",
    inputSchema: z.object({
      proposalId: z.string().uuid("ID da proposta inválido"),
      type: z.enum(["discount", "fee"]),
      amount: z.number().positive("Valor deve ser positivo"),
    }),
  },
};
