/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerifySerialRouteImport } from './routes/verify.$serial'
import { Route as PAgency_slugRouteImport } from './routes/p.$agency_slug'
import { Route as ClientTripsRouteImport } from './routes/client.trips'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientPaymentsRouteImport } from './routes/client.payments'
import { Route as ClientNotificationsRouteImport } from './routes/client.notifications'
import { Route as ClientGiftcardsRouteImport } from './routes/client.giftcards'
import { Route as ClientDocumentsRouteImport } from './routes/client.documents'
import { Route as ClientCouponsRouteImport } from './routes/client.coupons'
import { Route as ClientConsentsRouteImport } from './routes/client.consents'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthOnboardingRouteImport } from './routes/auth.onboarding'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AgencySlugRouteImport } from './routes/agency.$slug'
import { Route as AdminTripsRouteImport } from './routes/admin.trips'
import { Route as AdminTravelersRouteImport } from './routes/admin.travelers'
import { Route as AdminPoliciesRouteImport } from './routes/admin.policies'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminBrandRouteImport } from './routes/admin.brand'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminAgenciesRouteImport } from './routes/admin.agencies'
import { Route as PAgency_slugIndexRouteImport } from './routes/p.$agency_slug.index'
import { Route as AgencySlugIndexRouteImport } from './routes/agency.$slug.index'
import { Route as PCorporateApproveRouteImport } from './routes/p.corporate.approve'
import { Route as PAgency_slugContactRouteImport } from './routes/p.$agency_slug.contact'
import { Route as PAgency_slugPage_slugRouteImport } from './routes/p.$agency_slug.$page_slug'
import { Route as MProposalTokenRouteImport } from './routes/m.proposal.$token'
import { Route as MPaymentTokenRouteImport } from './routes/m.payment.$token'
import { Route as MPassengerTokenRouteImport } from './routes/m.passenger.$token'
import { Route as MInviteTokenRouteImport } from './routes/m.invite.$token'
import { Route as MContractTokenRouteImport } from './routes/m.contract.$token'
import { Route as MCheckinTokenRouteImport } from './routes/m.checkin.$token'
import { Route as ClientTripsIdRouteImport } from './routes/client.trips.$id'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as AgencySlugVouchersRouteImport } from './routes/agency.$slug.vouchers'
import { Route as AgencySlugVisasCatalogRouteImport } from './routes/agency.$slug.visas-catalog'
import { Route as AgencySlugVisasRouteImport } from './routes/agency.$slug.visas'
import { Route as AgencySlugTripsRouteImport } from './routes/agency.$slug.trips'
import { Route as AgencySlugTeamRouteImport } from './routes/agency.$slug.team'
import { Route as AgencySlugSupportRouteImport } from './routes/agency.$slug.support'
import { Route as AgencySlugSuppliersRouteImport } from './routes/agency.$slug.suppliers'
import { Route as AgencySlugSettingsRouteImport } from './routes/agency.$slug.settings'
import { Route as AgencySlugProposalsRouteImport } from './routes/agency.$slug.proposals'
import { Route as AgencySlugPortalRouteImport } from './routes/agency.$slug.portal'
import { Route as AgencySlugKnowledgeRouteImport } from './routes/agency.$slug.knowledge'
import { Route as AgencySlugGroupToursRouteImport } from './routes/agency.$slug.group-tours'
import { Route as AgencySlugFinancialRouteImport } from './routes/agency.$slug.financial'
import { Route as AgencySlugCrmRouteImport } from './routes/agency.$slug.crm'
import { Route as AgencySlugCorporateRouteImport } from './routes/agency.$slug.corporate'
import { Route as AgencySlugContractsRouteImport } from './routes/agency.$slug.contracts'
import { Route as AgencySlugCompetitorsRouteImport } from './routes/agency.$slug.competitors'
import { Route as AgencySlugCompanyRouteImport } from './routes/agency.$slug.company'
import { Route as AgencySlugClientsRouteImport } from './routes/agency.$slug.clients'
import { Route as AgencySlugBusLayoutsRouteImport } from './routes/agency.$slug.bus-layouts'
import { Route as AgencySlugBrandRouteImport } from './routes/agency.$slug.brand'
import { Route as AgencySlugBoardingRouteImport } from './routes/agency.$slug.boarding'
import { Route as AdminAgenciesIdRouteImport } from './routes/admin.agencies.$id'
import { Route as PAgency_slugKbIndexRouteImport } from './routes/p.$agency_slug.kb.index'
import { Route as AgencySlugPortalIndexRouteImport } from './routes/agency.$slug.portal.index'
import { Route as PAgency_slugVisaIdRouteImport } from './routes/p.$agency_slug.visa.$id'
import { Route as PAgency_slugTourIdRouteImport } from './routes/p.$agency_slug.tour.$id'
import { Route as PAgency_slugKbSlugRouteImport } from './routes/p.$agency_slug.kb.$slug'
import { Route as PAgency_slugBlogSlugRouteImport } from './routes/p.$agency_slug.blog.$slug'
import { Route as ApiPublicSitemapAgency_slugRouteImport } from './routes/api/public/sitemap.$agency_slug'
import { Route as AgencySlugTripsIdRouteImport } from './routes/agency.$slug.trips.$id'
import { Route as AgencySlugSupportTicket_idRouteImport } from './routes/agency.$slug.support.$ticket_id'
import { Route as AgencySlugProposalsNewRouteImport } from './routes/agency.$slug.proposals.new'
import { Route as AgencySlugProposalsIdRouteImport } from './routes/agency.$slug.proposals.$id'
import { Route as AgencySlugPortalPagesRouteImport } from './routes/agency.$slug.portal.pages'
import { Route as AgencySlugPortalBlogRouteImport } from './routes/agency.$slug.portal.blog'
import { Route as AgencySlugGroupToursIdRouteImport } from './routes/agency.$slug.group-tours.$id'
import { Route as AgencySlugFinancialInvoicesRouteImport } from './routes/agency.$slug.financial.invoices'
import { Route as AgencySlugFinancialDreRouteImport } from './routes/agency.$slug.financial.dre'
import { Route as AgencySlugFinancialCashRouteImport } from './routes/agency.$slug.financial.cash'
import { Route as AgencySlugCrmLead_idRouteImport } from './routes/agency.$slug.crm.$lead_id'
import { Route as AgencySlugCorporateRfp_idRouteImport } from './routes/agency.$slug.corporate.$rfp_id'
import { Route as AgencySlugClientsIdRouteImport } from './routes/agency.$slug.clients.$id'
import { Route as AgencySlugBusLayoutsIdRouteImport } from './routes/agency.$slug.bus-layouts.$id'
import { Route as AgencySlugTripsIdIndexRouteImport } from './routes/agency.$slug.trips.$id.index'
import { Route as AgencySlugTripsIdVouchersRouteImport } from './routes/agency.$slug.trips.$id.vouchers'
import { Route as AgencySlugTripsIdPassengersRouteImport } from './routes/agency.$slug.trips.$id.passengers'
import { Route as AgencySlugTripsIdFinancialRouteImport } from './routes/agency.$slug.trips.$id.financial'
import { Route as AgencySlugTripsIdContractRouteImport } from './routes/agency.$slug.trips.$id.contract'
import { Route as AgencySlugProposalsIdPreviewRouteImport } from './routes/agency.$slug.proposals.$id.preview'
import { Route as AgencySlugPortalPagesPage_idRouteImport } from './routes/agency.$slug.portal.pages.$page_id'

const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifySerialRoute = VerifySerialRouteImport.update({
  id: '/verify/$serial',
  path: '/verify/$serial',
  getParentRoute: () => rootRouteImport,
} as any)
const PAgency_slugRoute = PAgency_slugRouteImport.update({
  id: '/p/$agency_slug',
  path: '/p/$agency_slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTripsRoute = ClientTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPaymentsRoute = ClientPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientRoute,
} as any)
const ClientGiftcardsRoute = ClientGiftcardsRouteImport.update({
  id: '/giftcards',
  path: '/giftcards',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDocumentsRoute = ClientDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCouponsRoute = ClientCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => ClientRoute,
} as any)
const ClientConsentsRoute = ClientConsentsRouteImport.update({
  id: '/consents',
  path: '/consents',
  getParentRoute: () => ClientRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AgencySlugRoute = AgencySlugRouteImport.update({
  id: '/agency/$slug',
  path: '/agency/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTravelersRoute = AdminTravelersRouteImport.update({
  id: '/travelers',
  path: '/travelers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandRoute = AdminBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgenciesRoute = AdminAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AdminRoute,
} as any)
const PAgency_slugIndexRoute = PAgency_slugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PAgency_slugRoute,
} as any)
const AgencySlugIndexRoute = AgencySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgencySlugRoute,
} as any)
const PCorporateApproveRoute = PCorporateApproveRouteImport.update({
  id: '/p/corporate/approve',
  path: '/p/corporate/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const PAgency_slugContactRoute = PAgency_slugContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PAgency_slugRoute,
} as any)
const PAgency_slugPage_slugRoute = PAgency_slugPage_slugRouteImport.update({
  id: '/$page_slug',
  path: '/$page_slug',
  getParentRoute: () => PAgency_slugRoute,
} as any)
const MProposalTokenRoute = MProposalTokenRouteImport.update({
  id: '/m/proposal/$token',
  path: '/m/proposal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MPaymentTokenRoute = MPaymentTokenRouteImport.update({
  id: '/m/payment/$token',
  path: '/m/payment/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MPassengerTokenRoute = MPassengerTokenRouteImport.update({
  id: '/m/passenger/$token',
  path: '/m/passenger/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MInviteTokenRoute = MInviteTokenRouteImport.update({
  id: '/m/invite/$token',
  path: '/m/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MContractTokenRoute = MContractTokenRouteImport.update({
  id: '/m/contract/$token',
  path: '/m/contract/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MCheckinTokenRoute = MCheckinTokenRouteImport.update({
  id: '/m/checkin/$token',
  path: '/m/checkin/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTripsIdRoute = ClientTripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientTripsRoute,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencySlugVouchersRoute = AgencySlugVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugVisasCatalogRoute = AgencySlugVisasCatalogRouteImport.update({
  id: '/visas-catalog',
  path: '/visas-catalog',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugVisasRoute = AgencySlugVisasRouteImport.update({
  id: '/visas',
  path: '/visas',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugTripsRoute = AgencySlugTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugTeamRoute = AgencySlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugSupportRoute = AgencySlugSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugSuppliersRoute = AgencySlugSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugSettingsRoute = AgencySlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugProposalsRoute = AgencySlugProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugPortalRoute = AgencySlugPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugKnowledgeRoute = AgencySlugKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugGroupToursRoute = AgencySlugGroupToursRouteImport.update({
  id: '/group-tours',
  path: '/group-tours',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugFinancialRoute = AgencySlugFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugCrmRoute = AgencySlugCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugCorporateRoute = AgencySlugCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugContractsRoute = AgencySlugContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugCompetitorsRoute = AgencySlugCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugCompanyRoute = AgencySlugCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugClientsRoute = AgencySlugClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugBusLayoutsRoute = AgencySlugBusLayoutsRouteImport.update({
  id: '/bus-layouts',
  path: '/bus-layouts',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugBrandRoute = AgencySlugBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AgencySlugBoardingRoute = AgencySlugBoardingRouteImport.update({
  id: '/boarding',
  path: '/boarding',
  getParentRoute: () => AgencySlugRoute,
} as any)
const AdminAgenciesIdRoute = AdminAgenciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAgenciesRoute,
} as any)
const PAgency_slugKbIndexRoute = PAgency_slugKbIndexRouteImport.update({
  id: '/kb/',
  path: '/kb/',
  getParentRoute: () => PAgency_slugRoute,
} as any)
const AgencySlugPortalIndexRoute = AgencySlugPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgencySlugPortalRoute,
} as any)
const PAgency_slugVisaIdRoute = PAgency_slugVisaIdRouteImport.update({
  id: '/visa/$id',
  path: '/visa/$id',
  getParentRoute: () => PAgency_slugRoute,
} as any)
const PAgency_slugTourIdRoute = PAgency_slugTourIdRouteImport.update({
  id: '/tour/$id',
  path: '/tour/$id',
  getParentRoute: () => PAgency_slugRoute,
} as any)
const PAgency_slugKbSlugRoute = PAgency_slugKbSlugRouteImport.update({
  id: '/kb/$slug',
  path: '/kb/$slug',
  getParentRoute: () => PAgency_slugRoute,
} as any)
const PAgency_slugBlogSlugRoute = PAgency_slugBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PAgency_slugRoute,
} as any)
const ApiPublicSitemapAgency_slugRoute =
  ApiPublicSitemapAgency_slugRouteImport.update({
    id: '/api/public/sitemap/$agency_slug',
    path: '/api/public/sitemap/$agency_slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgencySlugTripsIdRoute = AgencySlugTripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgencySlugTripsRoute,
} as any)
const AgencySlugSupportTicket_idRoute =
  AgencySlugSupportTicket_idRouteImport.update({
    id: '/$ticket_id',
    path: '/$ticket_id',
    getParentRoute: () => AgencySlugSupportRoute,
  } as any)
const AgencySlugProposalsNewRoute = AgencySlugProposalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AgencySlugProposalsRoute,
} as any)
const AgencySlugProposalsIdRoute = AgencySlugProposalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgencySlugProposalsRoute,
} as any)
const AgencySlugPortalPagesRoute = AgencySlugPortalPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AgencySlugPortalRoute,
} as any)
const AgencySlugPortalBlogRoute = AgencySlugPortalBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AgencySlugPortalRoute,
} as any)
const AgencySlugGroupToursIdRoute = AgencySlugGroupToursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgencySlugGroupToursRoute,
} as any)
const AgencySlugFinancialInvoicesRoute =
  AgencySlugFinancialInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AgencySlugFinancialRoute,
  } as any)
const AgencySlugFinancialDreRoute = AgencySlugFinancialDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AgencySlugFinancialRoute,
} as any)
const AgencySlugFinancialCashRoute = AgencySlugFinancialCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AgencySlugFinancialRoute,
} as any)
const AgencySlugCrmLead_idRoute = AgencySlugCrmLead_idRouteImport.update({
  id: '/$lead_id',
  path: '/$lead_id',
  getParentRoute: () => AgencySlugCrmRoute,
} as any)
const AgencySlugCorporateRfp_idRoute =
  AgencySlugCorporateRfp_idRouteImport.update({
    id: '/$rfp_id',
    path: '/$rfp_id',
    getParentRoute: () => AgencySlugCorporateRoute,
  } as any)
const AgencySlugClientsIdRoute = AgencySlugClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgencySlugClientsRoute,
} as any)
const AgencySlugBusLayoutsIdRoute = AgencySlugBusLayoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgencySlugBusLayoutsRoute,
} as any)
const AgencySlugTripsIdIndexRoute = AgencySlugTripsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgencySlugTripsIdRoute,
} as any)
const AgencySlugTripsIdVouchersRoute =
  AgencySlugTripsIdVouchersRouteImport.update({
    id: '/vouchers',
    path: '/vouchers',
    getParentRoute: () => AgencySlugTripsIdRoute,
  } as any)
const AgencySlugTripsIdPassengersRoute =
  AgencySlugTripsIdPassengersRouteImport.update({
    id: '/passengers',
    path: '/passengers',
    getParentRoute: () => AgencySlugTripsIdRoute,
  } as any)
const AgencySlugTripsIdFinancialRoute =
  AgencySlugTripsIdFinancialRouteImport.update({
    id: '/financial',
    path: '/financial',
    getParentRoute: () => AgencySlugTripsIdRoute,
  } as any)
const AgencySlugTripsIdContractRoute =
  AgencySlugTripsIdContractRouteImport.update({
    id: '/contract',
    path: '/contract',
    getParentRoute: () => AgencySlugTripsIdRoute,
  } as any)
const AgencySlugProposalsIdPreviewRoute =
  AgencySlugProposalsIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AgencySlugProposalsIdRoute,
  } as any)
const AgencySlugPortalPagesPage_idRoute =
  AgencySlugPortalPagesPage_idRouteImport.update({
    id: '/$page_id',
    path: '/$page_id',
    getParentRoute: () => AgencySlugPortalPagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/admin/agencies': typeof AdminAgenciesRouteWithChildren
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/brand': typeof AdminBrandRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/travelers': typeof AdminTravelersRoute
  '/admin/trips': typeof AdminTripsRoute
  '/agency/$slug': typeof AgencySlugRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/client/consents': typeof ClientConsentsRoute
  '/client/coupons': typeof ClientCouponsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/giftcards': typeof ClientGiftcardsRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/trips': typeof ClientTripsRouteWithChildren
  '/p/$agency_slug': typeof PAgency_slugRouteWithChildren
  '/verify/$serial': typeof VerifySerialRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/agencies/$id': typeof AdminAgenciesIdRoute
  '/agency/$slug/boarding': typeof AgencySlugBoardingRoute
  '/agency/$slug/brand': typeof AgencySlugBrandRoute
  '/agency/$slug/bus-layouts': typeof AgencySlugBusLayoutsRouteWithChildren
  '/agency/$slug/clients': typeof AgencySlugClientsRouteWithChildren
  '/agency/$slug/company': typeof AgencySlugCompanyRoute
  '/agency/$slug/competitors': typeof AgencySlugCompetitorsRoute
  '/agency/$slug/contracts': typeof AgencySlugContractsRoute
  '/agency/$slug/corporate': typeof AgencySlugCorporateRouteWithChildren
  '/agency/$slug/crm': typeof AgencySlugCrmRouteWithChildren
  '/agency/$slug/financial': typeof AgencySlugFinancialRouteWithChildren
  '/agency/$slug/group-tours': typeof AgencySlugGroupToursRouteWithChildren
  '/agency/$slug/knowledge': typeof AgencySlugKnowledgeRoute
  '/agency/$slug/portal': typeof AgencySlugPortalRouteWithChildren
  '/agency/$slug/proposals': typeof AgencySlugProposalsRouteWithChildren
  '/agency/$slug/settings': typeof AgencySlugSettingsRoute
  '/agency/$slug/suppliers': typeof AgencySlugSuppliersRoute
  '/agency/$slug/support': typeof AgencySlugSupportRouteWithChildren
  '/agency/$slug/team': typeof AgencySlugTeamRoute
  '/agency/$slug/trips': typeof AgencySlugTripsRouteWithChildren
  '/agency/$slug/visas': typeof AgencySlugVisasRoute
  '/agency/$slug/visas-catalog': typeof AgencySlugVisasCatalogRoute
  '/agency/$slug/vouchers': typeof AgencySlugVouchersRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/client/trips/$id': typeof ClientTripsIdRoute
  '/m/checkin/$token': typeof MCheckinTokenRoute
  '/m/contract/$token': typeof MContractTokenRoute
  '/m/invite/$token': typeof MInviteTokenRoute
  '/m/passenger/$token': typeof MPassengerTokenRoute
  '/m/payment/$token': typeof MPaymentTokenRoute
  '/m/proposal/$token': typeof MProposalTokenRoute
  '/p/$agency_slug/$page_slug': typeof PAgency_slugPage_slugRoute
  '/p/$agency_slug/contact': typeof PAgency_slugContactRoute
  '/p/corporate/approve': typeof PCorporateApproveRoute
  '/agency/$slug/': typeof AgencySlugIndexRoute
  '/p/$agency_slug/': typeof PAgency_slugIndexRoute
  '/agency/$slug/bus-layouts/$id': typeof AgencySlugBusLayoutsIdRoute
  '/agency/$slug/clients/$id': typeof AgencySlugClientsIdRoute
  '/agency/$slug/corporate/$rfp_id': typeof AgencySlugCorporateRfp_idRoute
  '/agency/$slug/crm/$lead_id': typeof AgencySlugCrmLead_idRoute
  '/agency/$slug/financial/cash': typeof AgencySlugFinancialCashRoute
  '/agency/$slug/financial/dre': typeof AgencySlugFinancialDreRoute
  '/agency/$slug/financial/invoices': typeof AgencySlugFinancialInvoicesRoute
  '/agency/$slug/group-tours/$id': typeof AgencySlugGroupToursIdRoute
  '/agency/$slug/portal/blog': typeof AgencySlugPortalBlogRoute
  '/agency/$slug/portal/pages': typeof AgencySlugPortalPagesRouteWithChildren
  '/agency/$slug/proposals/$id': typeof AgencySlugProposalsIdRouteWithChildren
  '/agency/$slug/proposals/new': typeof AgencySlugProposalsNewRoute
  '/agency/$slug/support/$ticket_id': typeof AgencySlugSupportTicket_idRoute
  '/agency/$slug/trips/$id': typeof AgencySlugTripsIdRouteWithChildren
  '/api/public/sitemap/$agency_slug': typeof ApiPublicSitemapAgency_slugRoute
  '/p/$agency_slug/blog/$slug': typeof PAgency_slugBlogSlugRoute
  '/p/$agency_slug/kb/$slug': typeof PAgency_slugKbSlugRoute
  '/p/$agency_slug/tour/$id': typeof PAgency_slugTourIdRoute
  '/p/$agency_slug/visa/$id': typeof PAgency_slugVisaIdRoute
  '/agency/$slug/portal/': typeof AgencySlugPortalIndexRoute
  '/p/$agency_slug/kb/': typeof PAgency_slugKbIndexRoute
  '/agency/$slug/portal/pages/$page_id': typeof AgencySlugPortalPagesPage_idRoute
  '/agency/$slug/proposals/$id/preview': typeof AgencySlugProposalsIdPreviewRoute
  '/agency/$slug/trips/$id/contract': typeof AgencySlugTripsIdContractRoute
  '/agency/$slug/trips/$id/financial': typeof AgencySlugTripsIdFinancialRoute
  '/agency/$slug/trips/$id/passengers': typeof AgencySlugTripsIdPassengersRoute
  '/agency/$slug/trips/$id/vouchers': typeof AgencySlugTripsIdVouchersRoute
  '/agency/$slug/trips/$id/': typeof AgencySlugTripsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/agencies': typeof AdminAgenciesRouteWithChildren
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/brand': typeof AdminBrandRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/travelers': typeof AdminTravelersRoute
  '/admin/trips': typeof AdminTripsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/client/consents': typeof ClientConsentsRoute
  '/client/coupons': typeof ClientCouponsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/giftcards': typeof ClientGiftcardsRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/trips': typeof ClientTripsRouteWithChildren
  '/verify/$serial': typeof VerifySerialRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/client': typeof ClientIndexRoute
  '/admin/agencies/$id': typeof AdminAgenciesIdRoute
  '/agency/$slug/boarding': typeof AgencySlugBoardingRoute
  '/agency/$slug/brand': typeof AgencySlugBrandRoute
  '/agency/$slug/bus-layouts': typeof AgencySlugBusLayoutsRouteWithChildren
  '/agency/$slug/clients': typeof AgencySlugClientsRouteWithChildren
  '/agency/$slug/company': typeof AgencySlugCompanyRoute
  '/agency/$slug/competitors': typeof AgencySlugCompetitorsRoute
  '/agency/$slug/contracts': typeof AgencySlugContractsRoute
  '/agency/$slug/corporate': typeof AgencySlugCorporateRouteWithChildren
  '/agency/$slug/crm': typeof AgencySlugCrmRouteWithChildren
  '/agency/$slug/financial': typeof AgencySlugFinancialRouteWithChildren
  '/agency/$slug/group-tours': typeof AgencySlugGroupToursRouteWithChildren
  '/agency/$slug/knowledge': typeof AgencySlugKnowledgeRoute
  '/agency/$slug/proposals': typeof AgencySlugProposalsRouteWithChildren
  '/agency/$slug/settings': typeof AgencySlugSettingsRoute
  '/agency/$slug/suppliers': typeof AgencySlugSuppliersRoute
  '/agency/$slug/support': typeof AgencySlugSupportRouteWithChildren
  '/agency/$slug/team': typeof AgencySlugTeamRoute
  '/agency/$slug/trips': typeof AgencySlugTripsRouteWithChildren
  '/agency/$slug/visas': typeof AgencySlugVisasRoute
  '/agency/$slug/visas-catalog': typeof AgencySlugVisasCatalogRoute
  '/agency/$slug/vouchers': typeof AgencySlugVouchersRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/client/trips/$id': typeof ClientTripsIdRoute
  '/m/checkin/$token': typeof MCheckinTokenRoute
  '/m/contract/$token': typeof MContractTokenRoute
  '/m/invite/$token': typeof MInviteTokenRoute
  '/m/passenger/$token': typeof MPassengerTokenRoute
  '/m/payment/$token': typeof MPaymentTokenRoute
  '/m/proposal/$token': typeof MProposalTokenRoute
  '/p/$agency_slug/$page_slug': typeof PAgency_slugPage_slugRoute
  '/p/$agency_slug/contact': typeof PAgency_slugContactRoute
  '/p/corporate/approve': typeof PCorporateApproveRoute
  '/agency/$slug': typeof AgencySlugIndexRoute
  '/p/$agency_slug': typeof PAgency_slugIndexRoute
  '/agency/$slug/bus-layouts/$id': typeof AgencySlugBusLayoutsIdRoute
  '/agency/$slug/clients/$id': typeof AgencySlugClientsIdRoute
  '/agency/$slug/corporate/$rfp_id': typeof AgencySlugCorporateRfp_idRoute
  '/agency/$slug/crm/$lead_id': typeof AgencySlugCrmLead_idRoute
  '/agency/$slug/financial/cash': typeof AgencySlugFinancialCashRoute
  '/agency/$slug/financial/dre': typeof AgencySlugFinancialDreRoute
  '/agency/$slug/financial/invoices': typeof AgencySlugFinancialInvoicesRoute
  '/agency/$slug/group-tours/$id': typeof AgencySlugGroupToursIdRoute
  '/agency/$slug/portal/blog': typeof AgencySlugPortalBlogRoute
  '/agency/$slug/portal/pages': typeof AgencySlugPortalPagesRouteWithChildren
  '/agency/$slug/proposals/$id': typeof AgencySlugProposalsIdRouteWithChildren
  '/agency/$slug/proposals/new': typeof AgencySlugProposalsNewRoute
  '/agency/$slug/support/$ticket_id': typeof AgencySlugSupportTicket_idRoute
  '/api/public/sitemap/$agency_slug': typeof ApiPublicSitemapAgency_slugRoute
  '/p/$agency_slug/blog/$slug': typeof PAgency_slugBlogSlugRoute
  '/p/$agency_slug/kb/$slug': typeof PAgency_slugKbSlugRoute
  '/p/$agency_slug/tour/$id': typeof PAgency_slugTourIdRoute
  '/p/$agency_slug/visa/$id': typeof PAgency_slugVisaIdRoute
  '/agency/$slug/portal': typeof AgencySlugPortalIndexRoute
  '/p/$agency_slug/kb': typeof PAgency_slugKbIndexRoute
  '/agency/$slug/portal/pages/$page_id': typeof AgencySlugPortalPagesPage_idRoute
  '/agency/$slug/proposals/$id/preview': typeof AgencySlugProposalsIdPreviewRoute
  '/agency/$slug/trips/$id/contract': typeof AgencySlugTripsIdContractRoute
  '/agency/$slug/trips/$id/financial': typeof AgencySlugTripsIdFinancialRoute
  '/agency/$slug/trips/$id/passengers': typeof AgencySlugTripsIdPassengersRoute
  '/agency/$slug/trips/$id/vouchers': typeof AgencySlugTripsIdVouchersRoute
  '/agency/$slug/trips/$id': typeof AgencySlugTripsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/admin/agencies': typeof AdminAgenciesRouteWithChildren
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/brand': typeof AdminBrandRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/travelers': typeof AdminTravelersRoute
  '/admin/trips': typeof AdminTripsRoute
  '/agency/$slug': typeof AgencySlugRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/client/consents': typeof ClientConsentsRoute
  '/client/coupons': typeof ClientCouponsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/giftcards': typeof ClientGiftcardsRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/trips': typeof ClientTripsRouteWithChildren
  '/p/$agency_slug': typeof PAgency_slugRouteWithChildren
  '/verify/$serial': typeof VerifySerialRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/agencies/$id': typeof AdminAgenciesIdRoute
  '/agency/$slug/boarding': typeof AgencySlugBoardingRoute
  '/agency/$slug/brand': typeof AgencySlugBrandRoute
  '/agency/$slug/bus-layouts': typeof AgencySlugBusLayoutsRouteWithChildren
  '/agency/$slug/clients': typeof AgencySlugClientsRouteWithChildren
  '/agency/$slug/company': typeof AgencySlugCompanyRoute
  '/agency/$slug/competitors': typeof AgencySlugCompetitorsRoute
  '/agency/$slug/contracts': typeof AgencySlugContractsRoute
  '/agency/$slug/corporate': typeof AgencySlugCorporateRouteWithChildren
  '/agency/$slug/crm': typeof AgencySlugCrmRouteWithChildren
  '/agency/$slug/financial': typeof AgencySlugFinancialRouteWithChildren
  '/agency/$slug/group-tours': typeof AgencySlugGroupToursRouteWithChildren
  '/agency/$slug/knowledge': typeof AgencySlugKnowledgeRoute
  '/agency/$slug/portal': typeof AgencySlugPortalRouteWithChildren
  '/agency/$slug/proposals': typeof AgencySlugProposalsRouteWithChildren
  '/agency/$slug/settings': typeof AgencySlugSettingsRoute
  '/agency/$slug/suppliers': typeof AgencySlugSuppliersRoute
  '/agency/$slug/support': typeof AgencySlugSupportRouteWithChildren
  '/agency/$slug/team': typeof AgencySlugTeamRoute
  '/agency/$slug/trips': typeof AgencySlugTripsRouteWithChildren
  '/agency/$slug/visas': typeof AgencySlugVisasRoute
  '/agency/$slug/visas-catalog': typeof AgencySlugVisasCatalogRoute
  '/agency/$slug/vouchers': typeof AgencySlugVouchersRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/client/trips/$id': typeof ClientTripsIdRoute
  '/m/checkin/$token': typeof MCheckinTokenRoute
  '/m/contract/$token': typeof MContractTokenRoute
  '/m/invite/$token': typeof MInviteTokenRoute
  '/m/passenger/$token': typeof MPassengerTokenRoute
  '/m/payment/$token': typeof MPaymentTokenRoute
  '/m/proposal/$token': typeof MProposalTokenRoute
  '/p/$agency_slug/$page_slug': typeof PAgency_slugPage_slugRoute
  '/p/$agency_slug/contact': typeof PAgency_slugContactRoute
  '/p/corporate/approve': typeof PCorporateApproveRoute
  '/agency/$slug/': typeof AgencySlugIndexRoute
  '/p/$agency_slug/': typeof PAgency_slugIndexRoute
  '/agency/$slug/bus-layouts/$id': typeof AgencySlugBusLayoutsIdRoute
  '/agency/$slug/clients/$id': typeof AgencySlugClientsIdRoute
  '/agency/$slug/corporate/$rfp_id': typeof AgencySlugCorporateRfp_idRoute
  '/agency/$slug/crm/$lead_id': typeof AgencySlugCrmLead_idRoute
  '/agency/$slug/financial/cash': typeof AgencySlugFinancialCashRoute
  '/agency/$slug/financial/dre': typeof AgencySlugFinancialDreRoute
  '/agency/$slug/financial/invoices': typeof AgencySlugFinancialInvoicesRoute
  '/agency/$slug/group-tours/$id': typeof AgencySlugGroupToursIdRoute
  '/agency/$slug/portal/blog': typeof AgencySlugPortalBlogRoute
  '/agency/$slug/portal/pages': typeof AgencySlugPortalPagesRouteWithChildren
  '/agency/$slug/proposals/$id': typeof AgencySlugProposalsIdRouteWithChildren
  '/agency/$slug/proposals/new': typeof AgencySlugProposalsNewRoute
  '/agency/$slug/support/$ticket_id': typeof AgencySlugSupportTicket_idRoute
  '/agency/$slug/trips/$id': typeof AgencySlugTripsIdRouteWithChildren
  '/api/public/sitemap/$agency_slug': typeof ApiPublicSitemapAgency_slugRoute
  '/p/$agency_slug/blog/$slug': typeof PAgency_slugBlogSlugRoute
  '/p/$agency_slug/kb/$slug': typeof PAgency_slugKbSlugRoute
  '/p/$agency_slug/tour/$id': typeof PAgency_slugTourIdRoute
  '/p/$agency_slug/visa/$id': typeof PAgency_slugVisaIdRoute
  '/agency/$slug/portal/': typeof AgencySlugPortalIndexRoute
  '/p/$agency_slug/kb/': typeof PAgency_slugKbIndexRoute
  '/agency/$slug/portal/pages/$page_id': typeof AgencySlugPortalPagesPage_idRoute
  '/agency/$slug/proposals/$id/preview': typeof AgencySlugProposalsIdPreviewRoute
  '/agency/$slug/trips/$id/contract': typeof AgencySlugTripsIdContractRoute
  '/agency/$slug/trips/$id/financial': typeof AgencySlugTripsIdFinancialRoute
  '/agency/$slug/trips/$id/passengers': typeof AgencySlugTripsIdPassengersRoute
  '/agency/$slug/trips/$id/vouchers': typeof AgencySlugTripsIdVouchersRoute
  '/agency/$slug/trips/$id/': typeof AgencySlugTripsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/client'
    | '/admin/agencies'
    | '/admin/agents'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/brand'
    | '/admin/contracts'
    | '/admin/integrations'
    | '/admin/plans'
    | '/admin/policies'
    | '/admin/travelers'
    | '/admin/trips'
    | '/agency/$slug'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/client/consents'
    | '/client/coupons'
    | '/client/documents'
    | '/client/giftcards'
    | '/client/notifications'
    | '/client/payments'
    | '/client/profile'
    | '/client/trips'
    | '/p/$agency_slug'
    | '/verify/$serial'
    | '/admin/'
    | '/auth/'
    | '/client/'
    | '/admin/agencies/$id'
    | '/agency/$slug/boarding'
    | '/agency/$slug/brand'
    | '/agency/$slug/bus-layouts'
    | '/agency/$slug/clients'
    | '/agency/$slug/company'
    | '/agency/$slug/competitors'
    | '/agency/$slug/contracts'
    | '/agency/$slug/corporate'
    | '/agency/$slug/crm'
    | '/agency/$slug/financial'
    | '/agency/$slug/group-tours'
    | '/agency/$slug/knowledge'
    | '/agency/$slug/portal'
    | '/agency/$slug/proposals'
    | '/agency/$slug/settings'
    | '/agency/$slug/suppliers'
    | '/agency/$slug/support'
    | '/agency/$slug/team'
    | '/agency/$slug/trips'
    | '/agency/$slug/visas'
    | '/agency/$slug/visas-catalog'
    | '/agency/$slug/vouchers'
    | '/api/public/manifest'
    | '/api/public/mcp'
    | '/client/trips/$id'
    | '/m/checkin/$token'
    | '/m/contract/$token'
    | '/m/invite/$token'
    | '/m/passenger/$token'
    | '/m/payment/$token'
    | '/m/proposal/$token'
    | '/p/$agency_slug/$page_slug'
    | '/p/$agency_slug/contact'
    | '/p/corporate/approve'
    | '/agency/$slug/'
    | '/p/$agency_slug/'
    | '/agency/$slug/bus-layouts/$id'
    | '/agency/$slug/clients/$id'
    | '/agency/$slug/corporate/$rfp_id'
    | '/agency/$slug/crm/$lead_id'
    | '/agency/$slug/financial/cash'
    | '/agency/$slug/financial/dre'
    | '/agency/$slug/financial/invoices'
    | '/agency/$slug/group-tours/$id'
    | '/agency/$slug/portal/blog'
    | '/agency/$slug/portal/pages'
    | '/agency/$slug/proposals/$id'
    | '/agency/$slug/proposals/new'
    | '/agency/$slug/support/$ticket_id'
    | '/agency/$slug/trips/$id'
    | '/api/public/sitemap/$agency_slug'
    | '/p/$agency_slug/blog/$slug'
    | '/p/$agency_slug/kb/$slug'
    | '/p/$agency_slug/tour/$id'
    | '/p/$agency_slug/visa/$id'
    | '/agency/$slug/portal/'
    | '/p/$agency_slug/kb/'
    | '/agency/$slug/portal/pages/$page_id'
    | '/agency/$slug/proposals/$id/preview'
    | '/agency/$slug/trips/$id/contract'
    | '/agency/$slug/trips/$id/financial'
    | '/agency/$slug/trips/$id/passengers'
    | '/agency/$slug/trips/$id/vouchers'
    | '/agency/$slug/trips/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/agencies'
    | '/admin/agents'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/brand'
    | '/admin/contracts'
    | '/admin/integrations'
    | '/admin/plans'
    | '/admin/policies'
    | '/admin/travelers'
    | '/admin/trips'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/client/consents'
    | '/client/coupons'
    | '/client/documents'
    | '/client/giftcards'
    | '/client/notifications'
    | '/client/payments'
    | '/client/profile'
    | '/client/trips'
    | '/verify/$serial'
    | '/admin'
    | '/auth'
    | '/client'
    | '/admin/agencies/$id'
    | '/agency/$slug/boarding'
    | '/agency/$slug/brand'
    | '/agency/$slug/bus-layouts'
    | '/agency/$slug/clients'
    | '/agency/$slug/company'
    | '/agency/$slug/competitors'
    | '/agency/$slug/contracts'
    | '/agency/$slug/corporate'
    | '/agency/$slug/crm'
    | '/agency/$slug/financial'
    | '/agency/$slug/group-tours'
    | '/agency/$slug/knowledge'
    | '/agency/$slug/proposals'
    | '/agency/$slug/settings'
    | '/agency/$slug/suppliers'
    | '/agency/$slug/support'
    | '/agency/$slug/team'
    | '/agency/$slug/trips'
    | '/agency/$slug/visas'
    | '/agency/$slug/visas-catalog'
    | '/agency/$slug/vouchers'
    | '/api/public/manifest'
    | '/api/public/mcp'
    | '/client/trips/$id'
    | '/m/checkin/$token'
    | '/m/contract/$token'
    | '/m/invite/$token'
    | '/m/passenger/$token'
    | '/m/payment/$token'
    | '/m/proposal/$token'
    | '/p/$agency_slug/$page_slug'
    | '/p/$agency_slug/contact'
    | '/p/corporate/approve'
    | '/agency/$slug'
    | '/p/$agency_slug'
    | '/agency/$slug/bus-layouts/$id'
    | '/agency/$slug/clients/$id'
    | '/agency/$slug/corporate/$rfp_id'
    | '/agency/$slug/crm/$lead_id'
    | '/agency/$slug/financial/cash'
    | '/agency/$slug/financial/dre'
    | '/agency/$slug/financial/invoices'
    | '/agency/$slug/group-tours/$id'
    | '/agency/$slug/portal/blog'
    | '/agency/$slug/portal/pages'
    | '/agency/$slug/proposals/$id'
    | '/agency/$slug/proposals/new'
    | '/agency/$slug/support/$ticket_id'
    | '/api/public/sitemap/$agency_slug'
    | '/p/$agency_slug/blog/$slug'
    | '/p/$agency_slug/kb/$slug'
    | '/p/$agency_slug/tour/$id'
    | '/p/$agency_slug/visa/$id'
    | '/agency/$slug/portal'
    | '/p/$agency_slug/kb'
    | '/agency/$slug/portal/pages/$page_id'
    | '/agency/$slug/proposals/$id/preview'
    | '/agency/$slug/trips/$id/contract'
    | '/agency/$slug/trips/$id/financial'
    | '/agency/$slug/trips/$id/passengers'
    | '/agency/$slug/trips/$id/vouchers'
    | '/agency/$slug/trips/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/client'
    | '/admin/agencies'
    | '/admin/agents'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/brand'
    | '/admin/contracts'
    | '/admin/integrations'
    | '/admin/plans'
    | '/admin/policies'
    | '/admin/travelers'
    | '/admin/trips'
    | '/agency/$slug'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/client/consents'
    | '/client/coupons'
    | '/client/documents'
    | '/client/giftcards'
    | '/client/notifications'
    | '/client/payments'
    | '/client/profile'
    | '/client/trips'
    | '/p/$agency_slug'
    | '/verify/$serial'
    | '/admin/'
    | '/auth/'
    | '/client/'
    | '/admin/agencies/$id'
    | '/agency/$slug/boarding'
    | '/agency/$slug/brand'
    | '/agency/$slug/bus-layouts'
    | '/agency/$slug/clients'
    | '/agency/$slug/company'
    | '/agency/$slug/competitors'
    | '/agency/$slug/contracts'
    | '/agency/$slug/corporate'
    | '/agency/$slug/crm'
    | '/agency/$slug/financial'
    | '/agency/$slug/group-tours'
    | '/agency/$slug/knowledge'
    | '/agency/$slug/portal'
    | '/agency/$slug/proposals'
    | '/agency/$slug/settings'
    | '/agency/$slug/suppliers'
    | '/agency/$slug/support'
    | '/agency/$slug/team'
    | '/agency/$slug/trips'
    | '/agency/$slug/visas'
    | '/agency/$slug/visas-catalog'
    | '/agency/$slug/vouchers'
    | '/api/public/manifest'
    | '/api/public/mcp'
    | '/client/trips/$id'
    | '/m/checkin/$token'
    | '/m/contract/$token'
    | '/m/invite/$token'
    | '/m/passenger/$token'
    | '/m/payment/$token'
    | '/m/proposal/$token'
    | '/p/$agency_slug/$page_slug'
    | '/p/$agency_slug/contact'
    | '/p/corporate/approve'
    | '/agency/$slug/'
    | '/p/$agency_slug/'
    | '/agency/$slug/bus-layouts/$id'
    | '/agency/$slug/clients/$id'
    | '/agency/$slug/corporate/$rfp_id'
    | '/agency/$slug/crm/$lead_id'
    | '/agency/$slug/financial/cash'
    | '/agency/$slug/financial/dre'
    | '/agency/$slug/financial/invoices'
    | '/agency/$slug/group-tours/$id'
    | '/agency/$slug/portal/blog'
    | '/agency/$slug/portal/pages'
    | '/agency/$slug/proposals/$id'
    | '/agency/$slug/proposals/new'
    | '/agency/$slug/support/$ticket_id'
    | '/agency/$slug/trips/$id'
    | '/api/public/sitemap/$agency_slug'
    | '/p/$agency_slug/blog/$slug'
    | '/p/$agency_slug/kb/$slug'
    | '/p/$agency_slug/tour/$id'
    | '/p/$agency_slug/visa/$id'
    | '/agency/$slug/portal/'
    | '/p/$agency_slug/kb/'
    | '/agency/$slug/portal/pages/$page_id'
    | '/agency/$slug/proposals/$id/preview'
    | '/agency/$slug/trips/$id/contract'
    | '/agency/$slug/trips/$id/financial'
    | '/agency/$slug/trips/$id/passengers'
    | '/agency/$slug/trips/$id/vouchers'
    | '/agency/$slug/trips/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  AgencySlugRoute: typeof AgencySlugRouteWithChildren
  PAgency_slugRoute: typeof PAgency_slugRouteWithChildren
  VerifySerialRoute: typeof VerifySerialRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  MCheckinTokenRoute: typeof MCheckinTokenRoute
  MContractTokenRoute: typeof MContractTokenRoute
  MInviteTokenRoute: typeof MInviteTokenRoute
  MPassengerTokenRoute: typeof MPassengerTokenRoute
  MPaymentTokenRoute: typeof MPaymentTokenRoute
  MProposalTokenRoute: typeof MProposalTokenRoute
  PCorporateApproveRoute: typeof PCorporateApproveRoute
  ApiPublicSitemapAgency_slugRoute: typeof ApiPublicSitemapAgency_slugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/$serial': {
      id: '/verify/$serial'
      path: '/verify/$serial'
      fullPath: '/verify/$serial'
      preLoaderRoute: typeof VerifySerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$agency_slug': {
      id: '/p/$agency_slug'
      path: '/p/$agency_slug'
      fullPath: '/p/$agency_slug'
      preLoaderRoute: typeof PAgency_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/trips': {
      id: '/client/trips'
      path: '/trips'
      fullPath: '/client/trips'
      preLoaderRoute: typeof ClientTripsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/payments': {
      id: '/client/payments'
      path: '/payments'
      fullPath: '/client/payments'
      preLoaderRoute: typeof ClientPaymentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/notifications': {
      id: '/client/notifications'
      path: '/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/giftcards': {
      id: '/client/giftcards'
      path: '/giftcards'
      fullPath: '/client/giftcards'
      preLoaderRoute: typeof ClientGiftcardsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/documents': {
      id: '/client/documents'
      path: '/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof ClientDocumentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/coupons': {
      id: '/client/coupons'
      path: '/coupons'
      fullPath: '/client/coupons'
      preLoaderRoute: typeof ClientCouponsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/consents': {
      id: '/client/consents'
      path: '/consents'
      fullPath: '/client/consents'
      preLoaderRoute: typeof ClientConsentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/agency/$slug': {
      id: '/agency/$slug'
      path: '/agency/$slug'
      fullPath: '/agency/$slug'
      preLoaderRoute: typeof AgencySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/travelers': {
      id: '/admin/travelers'
      path: '/travelers'
      fullPath: '/admin/travelers'
      preLoaderRoute: typeof AdminTravelersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brand': {
      id: '/admin/brand'
      path: '/brand'
      fullPath: '/admin/brand'
      preLoaderRoute: typeof AdminBrandRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agencies': {
      id: '/admin/agencies'
      path: '/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AdminAgenciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/p/$agency_slug/': {
      id: '/p/$agency_slug/'
      path: '/'
      fullPath: '/p/$agency_slug/'
      preLoaderRoute: typeof PAgency_slugIndexRouteImport
      parentRoute: typeof PAgency_slugRoute
    }
    '/agency/$slug/': {
      id: '/agency/$slug/'
      path: '/'
      fullPath: '/agency/$slug/'
      preLoaderRoute: typeof AgencySlugIndexRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/p/corporate/approve': {
      id: '/p/corporate/approve'
      path: '/p/corporate/approve'
      fullPath: '/p/corporate/approve'
      preLoaderRoute: typeof PCorporateApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$agency_slug/contact': {
      id: '/p/$agency_slug/contact'
      path: '/contact'
      fullPath: '/p/$agency_slug/contact'
      preLoaderRoute: typeof PAgency_slugContactRouteImport
      parentRoute: typeof PAgency_slugRoute
    }
    '/p/$agency_slug/$page_slug': {
      id: '/p/$agency_slug/$page_slug'
      path: '/$page_slug'
      fullPath: '/p/$agency_slug/$page_slug'
      preLoaderRoute: typeof PAgency_slugPage_slugRouteImport
      parentRoute: typeof PAgency_slugRoute
    }
    '/m/proposal/$token': {
      id: '/m/proposal/$token'
      path: '/m/proposal/$token'
      fullPath: '/m/proposal/$token'
      preLoaderRoute: typeof MProposalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/payment/$token': {
      id: '/m/payment/$token'
      path: '/m/payment/$token'
      fullPath: '/m/payment/$token'
      preLoaderRoute: typeof MPaymentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/passenger/$token': {
      id: '/m/passenger/$token'
      path: '/m/passenger/$token'
      fullPath: '/m/passenger/$token'
      preLoaderRoute: typeof MPassengerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/invite/$token': {
      id: '/m/invite/$token'
      path: '/m/invite/$token'
      fullPath: '/m/invite/$token'
      preLoaderRoute: typeof MInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/contract/$token': {
      id: '/m/contract/$token'
      path: '/m/contract/$token'
      fullPath: '/m/contract/$token'
      preLoaderRoute: typeof MContractTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/checkin/$token': {
      id: '/m/checkin/$token'
      path: '/m/checkin/$token'
      fullPath: '/m/checkin/$token'
      preLoaderRoute: typeof MCheckinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/trips/$id': {
      id: '/client/trips/$id'
      path: '/$id'
      fullPath: '/client/trips/$id'
      preLoaderRoute: typeof ClientTripsIdRouteImport
      parentRoute: typeof ClientTripsRoute
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/$slug/vouchers': {
      id: '/agency/$slug/vouchers'
      path: '/vouchers'
      fullPath: '/agency/$slug/vouchers'
      preLoaderRoute: typeof AgencySlugVouchersRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/visas-catalog': {
      id: '/agency/$slug/visas-catalog'
      path: '/visas-catalog'
      fullPath: '/agency/$slug/visas-catalog'
      preLoaderRoute: typeof AgencySlugVisasCatalogRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/visas': {
      id: '/agency/$slug/visas'
      path: '/visas'
      fullPath: '/agency/$slug/visas'
      preLoaderRoute: typeof AgencySlugVisasRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/trips': {
      id: '/agency/$slug/trips'
      path: '/trips'
      fullPath: '/agency/$slug/trips'
      preLoaderRoute: typeof AgencySlugTripsRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/team': {
      id: '/agency/$slug/team'
      path: '/team'
      fullPath: '/agency/$slug/team'
      preLoaderRoute: typeof AgencySlugTeamRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/support': {
      id: '/agency/$slug/support'
      path: '/support'
      fullPath: '/agency/$slug/support'
      preLoaderRoute: typeof AgencySlugSupportRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/suppliers': {
      id: '/agency/$slug/suppliers'
      path: '/suppliers'
      fullPath: '/agency/$slug/suppliers'
      preLoaderRoute: typeof AgencySlugSuppliersRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/settings': {
      id: '/agency/$slug/settings'
      path: '/settings'
      fullPath: '/agency/$slug/settings'
      preLoaderRoute: typeof AgencySlugSettingsRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/proposals': {
      id: '/agency/$slug/proposals'
      path: '/proposals'
      fullPath: '/agency/$slug/proposals'
      preLoaderRoute: typeof AgencySlugProposalsRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/portal': {
      id: '/agency/$slug/portal'
      path: '/portal'
      fullPath: '/agency/$slug/portal'
      preLoaderRoute: typeof AgencySlugPortalRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/knowledge': {
      id: '/agency/$slug/knowledge'
      path: '/knowledge'
      fullPath: '/agency/$slug/knowledge'
      preLoaderRoute: typeof AgencySlugKnowledgeRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/group-tours': {
      id: '/agency/$slug/group-tours'
      path: '/group-tours'
      fullPath: '/agency/$slug/group-tours'
      preLoaderRoute: typeof AgencySlugGroupToursRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/financial': {
      id: '/agency/$slug/financial'
      path: '/financial'
      fullPath: '/agency/$slug/financial'
      preLoaderRoute: typeof AgencySlugFinancialRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/crm': {
      id: '/agency/$slug/crm'
      path: '/crm'
      fullPath: '/agency/$slug/crm'
      preLoaderRoute: typeof AgencySlugCrmRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/corporate': {
      id: '/agency/$slug/corporate'
      path: '/corporate'
      fullPath: '/agency/$slug/corporate'
      preLoaderRoute: typeof AgencySlugCorporateRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/contracts': {
      id: '/agency/$slug/contracts'
      path: '/contracts'
      fullPath: '/agency/$slug/contracts'
      preLoaderRoute: typeof AgencySlugContractsRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/competitors': {
      id: '/agency/$slug/competitors'
      path: '/competitors'
      fullPath: '/agency/$slug/competitors'
      preLoaderRoute: typeof AgencySlugCompetitorsRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/company': {
      id: '/agency/$slug/company'
      path: '/company'
      fullPath: '/agency/$slug/company'
      preLoaderRoute: typeof AgencySlugCompanyRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/clients': {
      id: '/agency/$slug/clients'
      path: '/clients'
      fullPath: '/agency/$slug/clients'
      preLoaderRoute: typeof AgencySlugClientsRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/bus-layouts': {
      id: '/agency/$slug/bus-layouts'
      path: '/bus-layouts'
      fullPath: '/agency/$slug/bus-layouts'
      preLoaderRoute: typeof AgencySlugBusLayoutsRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/brand': {
      id: '/agency/$slug/brand'
      path: '/brand'
      fullPath: '/agency/$slug/brand'
      preLoaderRoute: typeof AgencySlugBrandRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/agency/$slug/boarding': {
      id: '/agency/$slug/boarding'
      path: '/boarding'
      fullPath: '/agency/$slug/boarding'
      preLoaderRoute: typeof AgencySlugBoardingRouteImport
      parentRoute: typeof AgencySlugRoute
    }
    '/admin/agencies/$id': {
      id: '/admin/agencies/$id'
      path: '/$id'
      fullPath: '/admin/agencies/$id'
      preLoaderRoute: typeof AdminAgenciesIdRouteImport
      parentRoute: typeof AdminAgenciesRoute
    }
    '/p/$agency_slug/kb/': {
      id: '/p/$agency_slug/kb/'
      path: '/kb'
      fullPath: '/p/$agency_slug/kb/'
      preLoaderRoute: typeof PAgency_slugKbIndexRouteImport
      parentRoute: typeof PAgency_slugRoute
    }
    '/agency/$slug/portal/': {
      id: '/agency/$slug/portal/'
      path: '/'
      fullPath: '/agency/$slug/portal/'
      preLoaderRoute: typeof AgencySlugPortalIndexRouteImport
      parentRoute: typeof AgencySlugPortalRoute
    }
    '/p/$agency_slug/visa/$id': {
      id: '/p/$agency_slug/visa/$id'
      path: '/visa/$id'
      fullPath: '/p/$agency_slug/visa/$id'
      preLoaderRoute: typeof PAgency_slugVisaIdRouteImport
      parentRoute: typeof PAgency_slugRoute
    }
    '/p/$agency_slug/tour/$id': {
      id: '/p/$agency_slug/tour/$id'
      path: '/tour/$id'
      fullPath: '/p/$agency_slug/tour/$id'
      preLoaderRoute: typeof PAgency_slugTourIdRouteImport
      parentRoute: typeof PAgency_slugRoute
    }
    '/p/$agency_slug/kb/$slug': {
      id: '/p/$agency_slug/kb/$slug'
      path: '/kb/$slug'
      fullPath: '/p/$agency_slug/kb/$slug'
      preLoaderRoute: typeof PAgency_slugKbSlugRouteImport
      parentRoute: typeof PAgency_slugRoute
    }
    '/p/$agency_slug/blog/$slug': {
      id: '/p/$agency_slug/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/p/$agency_slug/blog/$slug'
      preLoaderRoute: typeof PAgency_slugBlogSlugRouteImport
      parentRoute: typeof PAgency_slugRoute
    }
    '/api/public/sitemap/$agency_slug': {
      id: '/api/public/sitemap/$agency_slug'
      path: '/api/public/sitemap/$agency_slug'
      fullPath: '/api/public/sitemap/$agency_slug'
      preLoaderRoute: typeof ApiPublicSitemapAgency_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/$slug/trips/$id': {
      id: '/agency/$slug/trips/$id'
      path: '/$id'
      fullPath: '/agency/$slug/trips/$id'
      preLoaderRoute: typeof AgencySlugTripsIdRouteImport
      parentRoute: typeof AgencySlugTripsRoute
    }
    '/agency/$slug/support/$ticket_id': {
      id: '/agency/$slug/support/$ticket_id'
      path: '/$ticket_id'
      fullPath: '/agency/$slug/support/$ticket_id'
      preLoaderRoute: typeof AgencySlugSupportTicket_idRouteImport
      parentRoute: typeof AgencySlugSupportRoute
    }
    '/agency/$slug/proposals/new': {
      id: '/agency/$slug/proposals/new'
      path: '/new'
      fullPath: '/agency/$slug/proposals/new'
      preLoaderRoute: typeof AgencySlugProposalsNewRouteImport
      parentRoute: typeof AgencySlugProposalsRoute
    }
    '/agency/$slug/proposals/$id': {
      id: '/agency/$slug/proposals/$id'
      path: '/$id'
      fullPath: '/agency/$slug/proposals/$id'
      preLoaderRoute: typeof AgencySlugProposalsIdRouteImport
      parentRoute: typeof AgencySlugProposalsRoute
    }
    '/agency/$slug/portal/pages': {
      id: '/agency/$slug/portal/pages'
      path: '/pages'
      fullPath: '/agency/$slug/portal/pages'
      preLoaderRoute: typeof AgencySlugPortalPagesRouteImport
      parentRoute: typeof AgencySlugPortalRoute
    }
    '/agency/$slug/portal/blog': {
      id: '/agency/$slug/portal/blog'
      path: '/blog'
      fullPath: '/agency/$slug/portal/blog'
      preLoaderRoute: typeof AgencySlugPortalBlogRouteImport
      parentRoute: typeof AgencySlugPortalRoute
    }
    '/agency/$slug/group-tours/$id': {
      id: '/agency/$slug/group-tours/$id'
      path: '/$id'
      fullPath: '/agency/$slug/group-tours/$id'
      preLoaderRoute: typeof AgencySlugGroupToursIdRouteImport
      parentRoute: typeof AgencySlugGroupToursRoute
    }
    '/agency/$slug/financial/invoices': {
      id: '/agency/$slug/financial/invoices'
      path: '/invoices'
      fullPath: '/agency/$slug/financial/invoices'
      preLoaderRoute: typeof AgencySlugFinancialInvoicesRouteImport
      parentRoute: typeof AgencySlugFinancialRoute
    }
    '/agency/$slug/financial/dre': {
      id: '/agency/$slug/financial/dre'
      path: '/dre'
      fullPath: '/agency/$slug/financial/dre'
      preLoaderRoute: typeof AgencySlugFinancialDreRouteImport
      parentRoute: typeof AgencySlugFinancialRoute
    }
    '/agency/$slug/financial/cash': {
      id: '/agency/$slug/financial/cash'
      path: '/cash'
      fullPath: '/agency/$slug/financial/cash'
      preLoaderRoute: typeof AgencySlugFinancialCashRouteImport
      parentRoute: typeof AgencySlugFinancialRoute
    }
    '/agency/$slug/crm/$lead_id': {
      id: '/agency/$slug/crm/$lead_id'
      path: '/$lead_id'
      fullPath: '/agency/$slug/crm/$lead_id'
      preLoaderRoute: typeof AgencySlugCrmLead_idRouteImport
      parentRoute: typeof AgencySlugCrmRoute
    }
    '/agency/$slug/corporate/$rfp_id': {
      id: '/agency/$slug/corporate/$rfp_id'
      path: '/$rfp_id'
      fullPath: '/agency/$slug/corporate/$rfp_id'
      preLoaderRoute: typeof AgencySlugCorporateRfp_idRouteImport
      parentRoute: typeof AgencySlugCorporateRoute
    }
    '/agency/$slug/clients/$id': {
      id: '/agency/$slug/clients/$id'
      path: '/$id'
      fullPath: '/agency/$slug/clients/$id'
      preLoaderRoute: typeof AgencySlugClientsIdRouteImport
      parentRoute: typeof AgencySlugClientsRoute
    }
    '/agency/$slug/bus-layouts/$id': {
      id: '/agency/$slug/bus-layouts/$id'
      path: '/$id'
      fullPath: '/agency/$slug/bus-layouts/$id'
      preLoaderRoute: typeof AgencySlugBusLayoutsIdRouteImport
      parentRoute: typeof AgencySlugBusLayoutsRoute
    }
    '/agency/$slug/trips/$id/': {
      id: '/agency/$slug/trips/$id/'
      path: '/'
      fullPath: '/agency/$slug/trips/$id/'
      preLoaderRoute: typeof AgencySlugTripsIdIndexRouteImport
      parentRoute: typeof AgencySlugTripsIdRoute
    }
    '/agency/$slug/trips/$id/vouchers': {
      id: '/agency/$slug/trips/$id/vouchers'
      path: '/vouchers'
      fullPath: '/agency/$slug/trips/$id/vouchers'
      preLoaderRoute: typeof AgencySlugTripsIdVouchersRouteImport
      parentRoute: typeof AgencySlugTripsIdRoute
    }
    '/agency/$slug/trips/$id/passengers': {
      id: '/agency/$slug/trips/$id/passengers'
      path: '/passengers'
      fullPath: '/agency/$slug/trips/$id/passengers'
      preLoaderRoute: typeof AgencySlugTripsIdPassengersRouteImport
      parentRoute: typeof AgencySlugTripsIdRoute
    }
    '/agency/$slug/trips/$id/financial': {
      id: '/agency/$slug/trips/$id/financial'
      path: '/financial'
      fullPath: '/agency/$slug/trips/$id/financial'
      preLoaderRoute: typeof AgencySlugTripsIdFinancialRouteImport
      parentRoute: typeof AgencySlugTripsIdRoute
    }
    '/agency/$slug/trips/$id/contract': {
      id: '/agency/$slug/trips/$id/contract'
      path: '/contract'
      fullPath: '/agency/$slug/trips/$id/contract'
      preLoaderRoute: typeof AgencySlugTripsIdContractRouteImport
      parentRoute: typeof AgencySlugTripsIdRoute
    }
    '/agency/$slug/proposals/$id/preview': {
      id: '/agency/$slug/proposals/$id/preview'
      path: '/preview'
      fullPath: '/agency/$slug/proposals/$id/preview'
      preLoaderRoute: typeof AgencySlugProposalsIdPreviewRouteImport
      parentRoute: typeof AgencySlugProposalsIdRoute
    }
    '/agency/$slug/portal/pages/$page_id': {
      id: '/agency/$slug/portal/pages/$page_id'
      path: '/$page_id'
      fullPath: '/agency/$slug/portal/pages/$page_id'
      preLoaderRoute: typeof AgencySlugPortalPagesPage_idRouteImport
      parentRoute: typeof AgencySlugPortalPagesRoute
    }
  }
}

interface AdminAgenciesRouteChildren {
  AdminAgenciesIdRoute: typeof AdminAgenciesIdRoute
}

const AdminAgenciesRouteChildren: AdminAgenciesRouteChildren = {
  AdminAgenciesIdRoute: AdminAgenciesIdRoute,
}

const AdminAgenciesRouteWithChildren = AdminAgenciesRoute._addFileChildren(
  AdminAgenciesRouteChildren,
)

interface AdminRouteChildren {
  AdminAgenciesRoute: typeof AdminAgenciesRouteWithChildren
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminBrandRoute: typeof AdminBrandRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminTravelersRoute: typeof AdminTravelersRoute
  AdminTripsRoute: typeof AdminTripsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgenciesRoute: AdminAgenciesRouteWithChildren,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminBrandRoute: AdminBrandRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminTravelersRoute: AdminTravelersRoute,
  AdminTripsRoute: AdminTripsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ClientTripsRouteChildren {
  ClientTripsIdRoute: typeof ClientTripsIdRoute
}

const ClientTripsRouteChildren: ClientTripsRouteChildren = {
  ClientTripsIdRoute: ClientTripsIdRoute,
}

const ClientTripsRouteWithChildren = ClientTripsRoute._addFileChildren(
  ClientTripsRouteChildren,
)

interface ClientRouteChildren {
  ClientConsentsRoute: typeof ClientConsentsRoute
  ClientCouponsRoute: typeof ClientCouponsRoute
  ClientDocumentsRoute: typeof ClientDocumentsRoute
  ClientGiftcardsRoute: typeof ClientGiftcardsRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientPaymentsRoute: typeof ClientPaymentsRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientTripsRoute: typeof ClientTripsRouteWithChildren
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientConsentsRoute: ClientConsentsRoute,
  ClientCouponsRoute: ClientCouponsRoute,
  ClientDocumentsRoute: ClientDocumentsRoute,
  ClientGiftcardsRoute: ClientGiftcardsRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientPaymentsRoute: ClientPaymentsRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientTripsRoute: ClientTripsRouteWithChildren,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface AgencySlugBusLayoutsRouteChildren {
  AgencySlugBusLayoutsIdRoute: typeof AgencySlugBusLayoutsIdRoute
}

const AgencySlugBusLayoutsRouteChildren: AgencySlugBusLayoutsRouteChildren = {
  AgencySlugBusLayoutsIdRoute: AgencySlugBusLayoutsIdRoute,
}

const AgencySlugBusLayoutsRouteWithChildren =
  AgencySlugBusLayoutsRoute._addFileChildren(AgencySlugBusLayoutsRouteChildren)

interface AgencySlugClientsRouteChildren {
  AgencySlugClientsIdRoute: typeof AgencySlugClientsIdRoute
}

const AgencySlugClientsRouteChildren: AgencySlugClientsRouteChildren = {
  AgencySlugClientsIdRoute: AgencySlugClientsIdRoute,
}

const AgencySlugClientsRouteWithChildren =
  AgencySlugClientsRoute._addFileChildren(AgencySlugClientsRouteChildren)

interface AgencySlugCorporateRouteChildren {
  AgencySlugCorporateRfp_idRoute: typeof AgencySlugCorporateRfp_idRoute
}

const AgencySlugCorporateRouteChildren: AgencySlugCorporateRouteChildren = {
  AgencySlugCorporateRfp_idRoute: AgencySlugCorporateRfp_idRoute,
}

const AgencySlugCorporateRouteWithChildren =
  AgencySlugCorporateRoute._addFileChildren(AgencySlugCorporateRouteChildren)

interface AgencySlugCrmRouteChildren {
  AgencySlugCrmLead_idRoute: typeof AgencySlugCrmLead_idRoute
}

const AgencySlugCrmRouteChildren: AgencySlugCrmRouteChildren = {
  AgencySlugCrmLead_idRoute: AgencySlugCrmLead_idRoute,
}

const AgencySlugCrmRouteWithChildren = AgencySlugCrmRoute._addFileChildren(
  AgencySlugCrmRouteChildren,
)

interface AgencySlugFinancialRouteChildren {
  AgencySlugFinancialCashRoute: typeof AgencySlugFinancialCashRoute
  AgencySlugFinancialDreRoute: typeof AgencySlugFinancialDreRoute
  AgencySlugFinancialInvoicesRoute: typeof AgencySlugFinancialInvoicesRoute
}

const AgencySlugFinancialRouteChildren: AgencySlugFinancialRouteChildren = {
  AgencySlugFinancialCashRoute: AgencySlugFinancialCashRoute,
  AgencySlugFinancialDreRoute: AgencySlugFinancialDreRoute,
  AgencySlugFinancialInvoicesRoute: AgencySlugFinancialInvoicesRoute,
}

const AgencySlugFinancialRouteWithChildren =
  AgencySlugFinancialRoute._addFileChildren(AgencySlugFinancialRouteChildren)

interface AgencySlugGroupToursRouteChildren {
  AgencySlugGroupToursIdRoute: typeof AgencySlugGroupToursIdRoute
}

const AgencySlugGroupToursRouteChildren: AgencySlugGroupToursRouteChildren = {
  AgencySlugGroupToursIdRoute: AgencySlugGroupToursIdRoute,
}

const AgencySlugGroupToursRouteWithChildren =
  AgencySlugGroupToursRoute._addFileChildren(AgencySlugGroupToursRouteChildren)

interface AgencySlugPortalPagesRouteChildren {
  AgencySlugPortalPagesPage_idRoute: typeof AgencySlugPortalPagesPage_idRoute
}

const AgencySlugPortalPagesRouteChildren: AgencySlugPortalPagesRouteChildren = {
  AgencySlugPortalPagesPage_idRoute: AgencySlugPortalPagesPage_idRoute,
}

const AgencySlugPortalPagesRouteWithChildren =
  AgencySlugPortalPagesRoute._addFileChildren(
    AgencySlugPortalPagesRouteChildren,
  )

interface AgencySlugPortalRouteChildren {
  AgencySlugPortalBlogRoute: typeof AgencySlugPortalBlogRoute
  AgencySlugPortalPagesRoute: typeof AgencySlugPortalPagesRouteWithChildren
  AgencySlugPortalIndexRoute: typeof AgencySlugPortalIndexRoute
}

const AgencySlugPortalRouteChildren: AgencySlugPortalRouteChildren = {
  AgencySlugPortalBlogRoute: AgencySlugPortalBlogRoute,
  AgencySlugPortalPagesRoute: AgencySlugPortalPagesRouteWithChildren,
  AgencySlugPortalIndexRoute: AgencySlugPortalIndexRoute,
}

const AgencySlugPortalRouteWithChildren =
  AgencySlugPortalRoute._addFileChildren(AgencySlugPortalRouteChildren)

interface AgencySlugProposalsIdRouteChildren {
  AgencySlugProposalsIdPreviewRoute: typeof AgencySlugProposalsIdPreviewRoute
}

const AgencySlugProposalsIdRouteChildren: AgencySlugProposalsIdRouteChildren = {
  AgencySlugProposalsIdPreviewRoute: AgencySlugProposalsIdPreviewRoute,
}

const AgencySlugProposalsIdRouteWithChildren =
  AgencySlugProposalsIdRoute._addFileChildren(
    AgencySlugProposalsIdRouteChildren,
  )

interface AgencySlugProposalsRouteChildren {
  AgencySlugProposalsIdRoute: typeof AgencySlugProposalsIdRouteWithChildren
  AgencySlugProposalsNewRoute: typeof AgencySlugProposalsNewRoute
}

const AgencySlugProposalsRouteChildren: AgencySlugProposalsRouteChildren = {
  AgencySlugProposalsIdRoute: AgencySlugProposalsIdRouteWithChildren,
  AgencySlugProposalsNewRoute: AgencySlugProposalsNewRoute,
}

const AgencySlugProposalsRouteWithChildren =
  AgencySlugProposalsRoute._addFileChildren(AgencySlugProposalsRouteChildren)

interface AgencySlugSupportRouteChildren {
  AgencySlugSupportTicket_idRoute: typeof AgencySlugSupportTicket_idRoute
}

const AgencySlugSupportRouteChildren: AgencySlugSupportRouteChildren = {
  AgencySlugSupportTicket_idRoute: AgencySlugSupportTicket_idRoute,
}

const AgencySlugSupportRouteWithChildren =
  AgencySlugSupportRoute._addFileChildren(AgencySlugSupportRouteChildren)

interface AgencySlugTripsIdRouteChildren {
  AgencySlugTripsIdContractRoute: typeof AgencySlugTripsIdContractRoute
  AgencySlugTripsIdFinancialRoute: typeof AgencySlugTripsIdFinancialRoute
  AgencySlugTripsIdPassengersRoute: typeof AgencySlugTripsIdPassengersRoute
  AgencySlugTripsIdVouchersRoute: typeof AgencySlugTripsIdVouchersRoute
  AgencySlugTripsIdIndexRoute: typeof AgencySlugTripsIdIndexRoute
}

const AgencySlugTripsIdRouteChildren: AgencySlugTripsIdRouteChildren = {
  AgencySlugTripsIdContractRoute: AgencySlugTripsIdContractRoute,
  AgencySlugTripsIdFinancialRoute: AgencySlugTripsIdFinancialRoute,
  AgencySlugTripsIdPassengersRoute: AgencySlugTripsIdPassengersRoute,
  AgencySlugTripsIdVouchersRoute: AgencySlugTripsIdVouchersRoute,
  AgencySlugTripsIdIndexRoute: AgencySlugTripsIdIndexRoute,
}

const AgencySlugTripsIdRouteWithChildren =
  AgencySlugTripsIdRoute._addFileChildren(AgencySlugTripsIdRouteChildren)

interface AgencySlugTripsRouteChildren {
  AgencySlugTripsIdRoute: typeof AgencySlugTripsIdRouteWithChildren
}

const AgencySlugTripsRouteChildren: AgencySlugTripsRouteChildren = {
  AgencySlugTripsIdRoute: AgencySlugTripsIdRouteWithChildren,
}

const AgencySlugTripsRouteWithChildren = AgencySlugTripsRoute._addFileChildren(
  AgencySlugTripsRouteChildren,
)

interface AgencySlugRouteChildren {
  AgencySlugBoardingRoute: typeof AgencySlugBoardingRoute
  AgencySlugBrandRoute: typeof AgencySlugBrandRoute
  AgencySlugBusLayoutsRoute: typeof AgencySlugBusLayoutsRouteWithChildren
  AgencySlugClientsRoute: typeof AgencySlugClientsRouteWithChildren
  AgencySlugCompanyRoute: typeof AgencySlugCompanyRoute
  AgencySlugCompetitorsRoute: typeof AgencySlugCompetitorsRoute
  AgencySlugContractsRoute: typeof AgencySlugContractsRoute
  AgencySlugCorporateRoute: typeof AgencySlugCorporateRouteWithChildren
  AgencySlugCrmRoute: typeof AgencySlugCrmRouteWithChildren
  AgencySlugFinancialRoute: typeof AgencySlugFinancialRouteWithChildren
  AgencySlugGroupToursRoute: typeof AgencySlugGroupToursRouteWithChildren
  AgencySlugKnowledgeRoute: typeof AgencySlugKnowledgeRoute
  AgencySlugPortalRoute: typeof AgencySlugPortalRouteWithChildren
  AgencySlugProposalsRoute: typeof AgencySlugProposalsRouteWithChildren
  AgencySlugSettingsRoute: typeof AgencySlugSettingsRoute
  AgencySlugSuppliersRoute: typeof AgencySlugSuppliersRoute
  AgencySlugSupportRoute: typeof AgencySlugSupportRouteWithChildren
  AgencySlugTeamRoute: typeof AgencySlugTeamRoute
  AgencySlugTripsRoute: typeof AgencySlugTripsRouteWithChildren
  AgencySlugVisasRoute: typeof AgencySlugVisasRoute
  AgencySlugVisasCatalogRoute: typeof AgencySlugVisasCatalogRoute
  AgencySlugVouchersRoute: typeof AgencySlugVouchersRoute
  AgencySlugIndexRoute: typeof AgencySlugIndexRoute
}

const AgencySlugRouteChildren: AgencySlugRouteChildren = {
  AgencySlugBoardingRoute: AgencySlugBoardingRoute,
  AgencySlugBrandRoute: AgencySlugBrandRoute,
  AgencySlugBusLayoutsRoute: AgencySlugBusLayoutsRouteWithChildren,
  AgencySlugClientsRoute: AgencySlugClientsRouteWithChildren,
  AgencySlugCompanyRoute: AgencySlugCompanyRoute,
  AgencySlugCompetitorsRoute: AgencySlugCompetitorsRoute,
  AgencySlugContractsRoute: AgencySlugContractsRoute,
  AgencySlugCorporateRoute: AgencySlugCorporateRouteWithChildren,
  AgencySlugCrmRoute: AgencySlugCrmRouteWithChildren,
  AgencySlugFinancialRoute: AgencySlugFinancialRouteWithChildren,
  AgencySlugGroupToursRoute: AgencySlugGroupToursRouteWithChildren,
  AgencySlugKnowledgeRoute: AgencySlugKnowledgeRoute,
  AgencySlugPortalRoute: AgencySlugPortalRouteWithChildren,
  AgencySlugProposalsRoute: AgencySlugProposalsRouteWithChildren,
  AgencySlugSettingsRoute: AgencySlugSettingsRoute,
  AgencySlugSuppliersRoute: AgencySlugSuppliersRoute,
  AgencySlugSupportRoute: AgencySlugSupportRouteWithChildren,
  AgencySlugTeamRoute: AgencySlugTeamRoute,
  AgencySlugTripsRoute: AgencySlugTripsRouteWithChildren,
  AgencySlugVisasRoute: AgencySlugVisasRoute,
  AgencySlugVisasCatalogRoute: AgencySlugVisasCatalogRoute,
  AgencySlugVouchersRoute: AgencySlugVouchersRoute,
  AgencySlugIndexRoute: AgencySlugIndexRoute,
}

const AgencySlugRouteWithChildren = AgencySlugRoute._addFileChildren(
  AgencySlugRouteChildren,
)

interface PAgency_slugRouteChildren {
  PAgency_slugPage_slugRoute: typeof PAgency_slugPage_slugRoute
  PAgency_slugContactRoute: typeof PAgency_slugContactRoute
  PAgency_slugIndexRoute: typeof PAgency_slugIndexRoute
  PAgency_slugBlogSlugRoute: typeof PAgency_slugBlogSlugRoute
  PAgency_slugKbSlugRoute: typeof PAgency_slugKbSlugRoute
  PAgency_slugTourIdRoute: typeof PAgency_slugTourIdRoute
  PAgency_slugVisaIdRoute: typeof PAgency_slugVisaIdRoute
  PAgency_slugKbIndexRoute: typeof PAgency_slugKbIndexRoute
}

const PAgency_slugRouteChildren: PAgency_slugRouteChildren = {
  PAgency_slugPage_slugRoute: PAgency_slugPage_slugRoute,
  PAgency_slugContactRoute: PAgency_slugContactRoute,
  PAgency_slugIndexRoute: PAgency_slugIndexRoute,
  PAgency_slugBlogSlugRoute: PAgency_slugBlogSlugRoute,
  PAgency_slugKbSlugRoute: PAgency_slugKbSlugRoute,
  PAgency_slugTourIdRoute: PAgency_slugTourIdRoute,
  PAgency_slugVisaIdRoute: PAgency_slugVisaIdRoute,
  PAgency_slugKbIndexRoute: PAgency_slugKbIndexRoute,
}

const PAgency_slugRouteWithChildren = PAgency_slugRoute._addFileChildren(
  PAgency_slugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  AgencySlugRoute: AgencySlugRouteWithChildren,
  PAgency_slugRoute: PAgency_slugRouteWithChildren,
  VerifySerialRoute: VerifySerialRoute,
  ApiPublicManifestRoute: ApiPublicManifestRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  MCheckinTokenRoute: MCheckinTokenRoute,
  MContractTokenRoute: MContractTokenRoute,
  MInviteTokenRoute: MInviteTokenRoute,
  MPassengerTokenRoute: MPassengerTokenRoute,
  MPaymentTokenRoute: MPaymentTokenRoute,
  MProposalTokenRoute: MProposalTokenRoute,
  PCorporateApproveRoute: PCorporateApproveRoute,
  ApiPublicSitemapAgency_slugRoute: ApiPublicSitemapAgency_slugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
